0.1.1 stable release - recommit with signature
Added an error code when entering invalid input

diff --git a/spgu b/spgu
--- a/spgu
+++ b/spgu
@@ -1,1 +1,89 @@
-This file is used for stable releases. There is nothing here right now. If you're seeing this, please use spgu-indev instead.
+#!/bin/bash
+echo "Welcome to Soul's Pretty Good Updater v0.1.1 for Debian based systems."
+echo "This software is licensed under GPL v3 and is provided as-is with no guarantee of suitability for a particular purpose. Use at your own risk."
+echo ""
+
+#VARIABLES
+#Modules
+	APTMOD="true"
+	FLATMOD="true"
+#Colors
+	GREEN=`echo -en "\e[32m"`
+	RED=`echo -en "\e[31m"`
+	NORMAL=`echo -en "\e[0m"`
+#Stable
+	ISSTABLE="true"
+
+#INDEV
+#This section warns the user they are using a development version of the application. Use the ISSTABLE variable above to control this.
+if [ "$ISSTABLE" == "true" ]
+then
+	:
+else
+	read -p "${RED}WARNING:${NORMAL} This is a development version - code may be unstable! Proceed anyways y/N? " ANSWERx
+	case "$ANSWERx" in
+		[yY])
+			echo "Proceeding..."
+			echo "Thank you for testing this software! Please report any bugs you find."
+			echo ""
+			;;
+		*)
+			echo "Aborted."
+			exit 0
+			;;
+	esac
+fi
+
+#MODULE CHECKS
+if [ "$APTMOD" == "true" ]
+then
+	echo "Base module is ${GREEN}ACTIVE${NORMAL}"
+else
+	echo "Base module is ${RED}INACTIVE${NORMAL}"
+fi
+if [ "$FLATMOD" == "true" ]
+then
+	echo "Flatpak module is ${GREEN}ACTIVE${NORMAL}"
+else
+	echo "Flatpak module is ${RED}INACTIVE${NORMAL}"
+fi
+echo "No custom modules found."
+echo ""
+
+#PROMPT
+#Apt update
+read -p "Would you like to update apt now Y/n? " ANSWER0
+case "$ANSWER0" in
+	"" | [yY])
+		sudo apt update && sudo apt upgrade -y
+		echo "Checking for unneeded dependencies..."
+		sudo apt autoremove -y
+		echo "Apt update complete!"
+		;;
+	[nN])
+		echo "Skipping this step..."
+		;;
+	*)
+		echo "${RED}ERROR:${NORMAL} Invalid response - Aborted."
+		exit 2
+		;;
+esac
+
+#Flatpak update
+read -p "Would you like to update flatpak now Y/n? " ANSWER1
+case "$ANSWER1" in
+	"" | [yY])
+		echo "Updating flatpak..."
+		flatpak update -y
+		echo "Checking for unneeded dependencies..."
+		flatpak uninstall --unused -y
+		echo "Flatpak update complete!"
+		;;
+	[nN])
+		echo "Thank you for your time! Goodbye!"
+		;;
+	*)
+		echo "${RED}ERROR:${NORMAL} Invalid response - Aborted."
+		exit 2
+		;;
+esac
